<?php
$schedule = $payments ?? [];
if ($schedule === [] && isset($record['pago_mes'])) {
    foreach ((array) $record['pago_mes'] as $i => $month) $schedule[]=['fecha_pago'=>$month.'-01','monto'=>((array)($record['pago_monto']??[]))[$i]??''];
}
?>
<div class="col-12 sale-schedule" data-sale-schedule data-amount="<?= esc($proposalAmount ?? 0,'attr') ?>">
 <div class="border rounded p-3"><div class="d-flex justify-content-between align-items-center mb-2"><h3 class="h6 mb-0">Distribución de pagos de la Venta</h3><button class="btn btn-sm btn-outline-primary" type="button" data-add-payment>Agregar cuota</button></div>
 <div data-payment-rows><?php foreach($schedule as $row): ?><div class="row g-2 mb-2 payment-row"><div class="col-md-5"><input class="form-control" type="month" name="pago_mes[]" value="<?= esc(substr((string)$row['fecha_pago'],0,7)) ?>"></div><div class="col-md-5"><input class="form-control payment-amount" type="number" min="0.01" step="0.01" name="pago_monto[]" value="<?= esc($row['monto']) ?>"></div><div class="col-md-2"><button class="btn btn-outline-danger w-100" type="button" data-remove-payment>Quitar</button></div></div><?php endforeach ?></div>
 <div class="small">Distribuido: <strong data-payment-total>$0.00</strong> · Restante: <strong data-payment-remaining>$0.00</strong></div></div>
</div>
<template data-payment-template><div class="row g-2 mb-2 payment-row"><div class="col-md-5"><input class="form-control" type="month" name="pago_mes[]"></div><div class="col-md-5"><input class="form-control payment-amount" type="number" min="0.01" step="0.01" name="pago_monto[]"></div><div class="col-md-2"><button class="btn btn-outline-danger w-100" type="button" data-remove-payment>Quitar</button></div></div></template>
<script>(function(){const root=document.querySelector('[data-sale-schedule]');if(!root)return;const rows=root.querySelector('[data-payment-rows]'),tpl=document.querySelector('[data-payment-template]'),proposal=document.querySelector('select[name="propuesta_id"]'),status=document.querySelector('select[name="estado_id"]');function calc(){if(proposal&&proposal.selectedOptions[0])root.dataset.amount=proposal.selectedOptions[0].dataset.amount||0;if(status)root.style.display=String(status.value)==='4'?'':'none';let t=0;root.querySelectorAll('.payment-amount').forEach(i=>t+=Number(i.value||0));root.querySelector('[data-payment-total]').textContent=t.toLocaleString('es-MX',{style:'currency',currency:'MXN'});root.querySelector('[data-payment-remaining]').textContent=(Number(root.dataset.amount||0)-t).toLocaleString('es-MX',{style:'currency',currency:'MXN'});}root.addEventListener('input',calc);if(proposal)proposal.addEventListener('change',calc);if(status)status.addEventListener('change',calc);root.addEventListener('click',e=>{if(e.target.closest('[data-add-payment]')){rows.append(tpl.content.cloneNode(true));calc()}if(e.target.closest('[data-remove-payment]')){e.target.closest('.payment-row').remove();calc()}});if(!rows.children.length)rows.append(tpl.content.cloneNode(true));calc()})();</script>
