<?php
use App\Services\AuthorizationService;use App\Services\ForecastService;use App\Services\ProposalPaymentService;use App\Services\SalesGoalService;use CodeIgniter\Test\CIUnitTestCase;use CodeIgniter\Test\FeatureTestTrait;use Config\Services;
final class SalesGoalForecastFeatureTest extends CIUnitTestCase
{
 use FeatureTestTrait;
 protected function setUp():void{parent::setUp();$db=db_connect();foreach(['propuesta_pago','meta_venta','propuesta','usuario_ucomercial','ucomercial','usuario','perfil'] as $t)$db->query('DROP TABLE IF EXISTS '.$db->escapeIdentifiers($db->prefixTable($t)));$sql=[
 'perfil'=>'id INTEGER PRIMARY KEY,nombre TEXT,deleted INTEGER DEFAULT 0','ucomercial'=>'id INTEGER PRIMARY KEY,nombre TEXT,deleted INTEGER DEFAULT 0','usuario'=>'id INTEGER PRIMARY KEY,nombre TEXT,perfil_id INTEGER,deleted INTEGER DEFAULT 0','usuario_ucomercial'=>'id INTEGER PRIMARY KEY AUTOINCREMENT,usuario_id INTEGER,ucomercial_id INTEGER,deleted INTEGER DEFAULT 0','meta_venta'=>'id INTEGER PRIMARY KEY AUTOINCREMENT,anio INTEGER,mes INTEGER,usuario_id INTEGER,ucomercial_id INTEGER,asignado_por INTEGER,monto NUMERIC,u_crea INTEGER,u_modifica INTEGER,f_creacion TEXT,f_modificacion TEXT,deleted INTEGER DEFAULT 0,UNIQUE(anio,mes,usuario_id,ucomercial_id)','propuesta'=>'id INTEGER PRIMARY KEY,nombre TEXT,monto NUMERIC,estado_id INTEGER,ejecutivo_id INTEGER,deleted INTEGER DEFAULT 0,u_modifica INTEGER,f_modificacion TEXT','propuesta_pago'=>'id INTEGER PRIMARY KEY AUTOINCREMENT,propuesta_id INTEGER,fecha_pago TEXT,monto NUMERIC,secuencia INTEGER,u_crea INTEGER,u_modifica INTEGER,f_creacion TEXT,f_modificacion TEXT,deleted INTEGER DEFAULT 0,UNIQUE(propuesta_id,secuencia)'];foreach($sql as $t=>$d)$db->query('CREATE TABLE '.$db->escapeIdentifiers($db->prefixTable($t)).' ('.$d.')');if(method_exists($db,'resetDataCache'))$db->resetDataCache();$db->table('perfil')->insertBatch([['id'=>1,'nombre'=>'Administrador'],['id'=>2,'nombre'=>'Gerente'],['id'=>3,'nombre'=>'Ejecutivo']]);$db->table('ucomercial')->insertBatch([['id'=>10,'nombre'=>'Norte'],['id'=>20,'nombre'=>'Sur']]);$db->table('usuario')->insertBatch([['id'=>1,'nombre'=>'Director','perfil_id'=>1],['id'=>2,'nombre'=>'Gerente Norte','perfil_id'=>2],['id'=>3,'nombre'=>'Ejecutivo Norte','perfil_id'=>3],['id'=>4,'nombre'=>'Ejecutivo Sur','perfil_id'=>3]]);$db->table('usuario_ucomercial')->insertBatch([['usuario_id'=>1,'ucomercial_id'=>10],['usuario_id'=>2,'ucomercial_id'=>10],['usuario_id'=>3,'ucomercial_id'=>10],['usuario_id'=>4,'ucomercial_id'=>20]]);$db->table('propuesta')->insert(['id'=>100,'nombre'=>'Venta','monto'=>100,'estado_id'=>1,'ejecutivo_id'=>3]);}
 public function testHierarchyAllocationSaleScheduleAndForecast():void{$goals=new SalesGoalService();$goals->save(['anio'=>2099,'mes'=>7,'usuario_id'=>2,'ucomercial_id'=>10,'monto'=>'1000.00'],$this->id(1,1,10));$goals->save(['anio'=>2099,'mes'=>7,'usuario_id'=>3,'ucomercial_id'=>10,'monto'=>'800.00'],$this->id(2,2,10));$this->expectExceptionMessage('supera');try{$goals->save(['anio'=>2099,'mes'=>7,'usuario_id'=>3,'ucomercial_id'=>10,'monto'=>'1200.00'],$this->id(2,2,10));}catch(Throwable $e){$this->assertSame(800.0,(float)db_connect()->table('meta_venta')->select('monto')->where('usuario_id',3)->get()->getRowArray()['monto']);throw $e;}}
 public function testPaymentCrossesYearsAndActualUsesInstallmentMonth():void{(new ProposalPaymentService())->registerSale(100,['pago_mes'=>['2026-12','2027-01'],'pago_monto'=>['40','60']],$this->id(3,3,10),'owner',3);$this->assertSame(4,(int)db_connect()->table('propuesta')->select('estado_id')->where('id',100)->get()->getRowArray()['estado_id']);$this->assertCount(2,db_connect()->table('propuesta_pago')->get()->getResultArray());$f=(new ForecastService())->annual(2027,$this->id(3,3,10));$this->assertSame(40.0,$f['previous'][11]);$this->assertSame(60.0,$f['actual'][0]);}
 public function testGoalsControllerVisibilitySaveAndExecutiveDenial():void{$manager=$this->session(2,2,10);(new SalesGoalService())->save(['anio'=>2099,'mes'=>8,'usuario_id'=>2,'ucomercial_id'=>10,'monto'=>'500'],$this->id(1,1,10));$page=$this->withSession($manager)->get('meta?anio=2099');$page->assertOK();$page->assertSee('Ejecutivo Norte');$page->assertSee('Guardar metas');$save=$this->withSession($manager)->post('meta/save',$this->csrf(['anio'=>2099,'metas'=>[3=>[10=>[8=>'250']]]]));$save->assertRedirectTo('meta?anio=2099');$this->assertSame(250.0,(float)db_connect()->table('meta_venta')->select('monto')->where(['usuario_id'=>3,'mes'=>8])->get()->getRowArray()['monto']);$denied=$this->withSession($this->session(3,3,10))->post('meta/save',$this->csrf(['anio'=>2099,'metas'=>[3=>[10=>[9=>'10']]]]));$denied->assertStatus(403);}
 public function testBatchIgnoresClosedMonthsAndSavesAugust():void{$service=new SalesGoalService();$service->saveBatch(['anio'=>2026,'metas'=>[2=>[10=>[1=>'99.00',8=>'250.00']]]],$this->id(1,1,10));$this->assertSame(0,db_connect()->table('meta_venta')->where(['usuario_id'=>2,'anio'=>2026,'mes'=>1])->countAllResults());$this->assertSame(250.0,(float)db_connect()->table('meta_venta')->select('monto')->where(['usuario_id'=>2,'anio'=>2026,'mes'=>8])->get()->getRowArray()['monto']);}
 private function id(int $profile,int $user,int $unit):array{return ['perfil_id'=>$profile,'user_id'=>$user,'ucomercial_id'=>$unit,'ucomercial_ids'=>[$unit]];}
 private function session(int $profile,int $user,int $unit):array{return ['user'=>$this->id($profile,$user,$unit)+['nombre'=>'Test','correo'=>'t@example.com','cgestion_id'=>1],'permissions'=>(new AuthorizationService())->permissionsForProfile($profile)];}
 private function csrf(array $data):array{$s=Services::security();$data[$s->getTokenName()]=$s->getHash();return $data;}
}
