<?php
namespace App\Services;
use App\Models\ProposalPaymentModel;use InvalidArgumentException;use RuntimeException;
final class ProposalPaymentService
{
 public function __construct(private readonly ProposalPaymentModel $model=new ProposalPaymentModel()){} public function forProposal(int $id):array{return db_connect()->tableExists('propuesta_pago')?$this->model->activeForProposal($id):[];}
 public function registerSale(int $proposalId,array $input,array $identity,string $scope,int $actorId):void
 {if(!db_connect()->tableExists('propuesta_pago'))throw new RuntimeException('La tabla de pagos no esta disponible.');$proposal=db_connect()->table('propuesta')->where(['id'=>$proposalId,'deleted'=>0])->get()->getRowArray();if($proposal===null)throw new InvalidArgumentException('La propuesta no esta disponible.');if((int)$proposal['ejecutivo_id']!==$actorId||(int)($identity['perfil_id']??0)!==3)throw new InvalidArgumentException('Solo el ejecutivo propietario puede registrar la Venta.');$months=(array)($input['pago_mes']??[]);$amounts=(array)($input['pago_monto']??[]);if($months===[]||count($months)!==count($amounts))throw new InvalidArgumentException('Captura al menos una cuota de pago.');$rows=[];$sum=0;foreach($months as $i=>$month){$month=(string)$month;$amount=(string)($amounts[$i]??'');if(!preg_match('/^\d{4}-(0[1-9]|1[0-2])$/',$month)||!preg_match('/^\d+(?:\.\d{1,2})?$/',$amount))throw new InvalidArgumentException('La distribucion de pagos contiene datos invalidos.');$cents=(int)round((float)$amount*100);if($cents<=0)throw new InvalidArgumentException('Cada cuota debe ser mayor a cero.');$sum+=$cents;$rows[]=['propuesta_id'=>$proposalId,'fecha_pago'=>$month.'-01','monto'=>number_format($cents/100,2,'.',''),'secuencia'=>$i+1,'u_crea'=>$actorId,'f_creacion'=>date('Y-m-d H:i:s'),'deleted'=>0];}if($sum!==(int)round((float)$proposal['monto']*100))throw new InvalidArgumentException('Las cuotas deben sumar exactamente el monto de la propuesta.');$now=date('Y-m-d H:i:s');$this->model->where('propuesta_id',$proposalId)->where('deleted',0)->set(['deleted'=>1,'u_modifica'=>$actorId,'f_modificacion'=>$now])->update();if(!$this->model->insertBatch($rows))throw new RuntimeException('No fue posible guardar la distribucion de pagos.');if(!db_connect()->table('propuesta')->where('id',$proposalId)->update(['estado_id'=>4,'u_modifica'=>$actorId,'f_modificacion'=>$now]))throw new RuntimeException('No fue posible registrar la Venta.');}
}
