<?php

use CodeIgniter\Router\RouteCollection;

/** @var RouteCollection $routes */
$routes->match(['GET', 'POST'], 'login', 'Auth::login');
$routes->get('logout', 'Auth::logout', ['filter' => 'auth']);
$routes->group('', ['filter' => 'auth'], static function ($routes): void {
    $routes->get('/', 'Home::index');
    $routes->get('home', 'Home::index');
    $routes->get('meta', 'Goals::index');
    $routes->post('meta/save', 'Goals::save');
    $routes->get('search', 'Compatibility::search');
    $routes->get('usuario', 'Users::index');
    $routes->match(['GET', 'POST'], 'usuario/add', 'Users::add');
    $routes->post('usuario/changeUC/(:num)', 'Users::changeUC/$1');
    $routes->get('usuario/transferAccount/(:num)', 'Users::transferAccount/$1');
    $routes->match(['GET', 'POST'], 'profile/(:num)', 'Users::edit/$1');
    $routes->match(['GET', 'POST'], 'usuario/(:num)', 'Users::edit/$1');
    $routes->match(['GET', 'POST'], 'auth/get_rows', 'Users::rows');
    $routes->post('auth/searchClient', 'Compatibility::searchClient');
    $routes->post('auth/delete/(:num)', 'Users::delete/$1');
    $routes->post('auth/transfering', 'Users::transfering');
    $routes->post('auth/processFileExcel', 'Imports::users');
    $routes->get('perfil', 'Profiles::index');
    $routes->match(['GET', 'POST'], 'perfil/add', 'Profiles::add');
    $routes->match(['GET', 'POST'], 'perfil/(:num)', 'Profiles::edit/$1');
    $routes->match(['GET', 'POST'], 'perfil/get_rows', 'Profiles::rows');
    $routes->get('cpotencial', 'Prospects::index');
    $routes->match(['GET', 'POST'], 'cpotencial/add', 'Prospects::add');
    $routes->match(['GET', 'POST'], 'cpotencial/(:num)', 'Prospects::edit/$1');
    $routes->match(['GET', 'POST'], 'cpotencial/get_rows', 'Prospects::rows');
    $routes->post('cpotencial/convert/(:num)', 'Prospects::convert/$1');
    $routes->post('cpotencial/delete/(:num)', 'Prospects::delete/$1');
    $routes->post('cpotencial/processFileExcel', 'Imports::prospects');
    $routes->post('cpotencial/vericarExistencia', 'Compatibility::prospectExists');
    $routes->get('cliente', 'Customers::index');
    $routes->match(['GET', 'POST'], 'cliente/add', 'Customers::add');
    $routes->match(['GET', 'POST'], 'cliente/(:num)', 'Customers::edit/$1');
    $routes->match(['GET', 'POST'], 'cliente/get_rows', 'Customers::rows');
    $routes->post('cliente/delete/(:num)', 'Customers::delete/$1');
    $routes->post('cliente/processFileExcel', 'Imports::customers');
    $routes->post('cliente/vericarExistencia', 'Compatibility::customerExists');
    $routes->get('contacto', 'Contacts::index');
    $routes->match(['GET', 'POST'], 'contacto/add', 'Contacts::add');
    $routes->match(['GET', 'POST'], 'contacto/(:num)', 'Contacts::edit/$1');
    $routes->match(['GET', 'POST'], 'contacto/get_rows', 'Contacts::rows');
    $routes->post('contacto/delete/(:num)', 'Contacts::delete/$1');
    $routes->get('contacto/subpanel', 'Contacts::subpanel');
    $routes->post('contacto/addSubpanel', 'Contacts::addSubpanel');
    $routes->post('contacto/get_rows_subpanel', 'Contacts::subpanelRows');
    $routes->get('documento', 'Documents::index');
    $routes->match(['GET', 'POST'], 'documento/get_rows', 'Documents::rows');
    $routes->get('documento/subpanel', 'Documents::subpanel');
    $routes->post('documento/addSubpanel', 'Documents::addSubpanel');
    $routes->post('documento/get_rows_subpanel', 'Documents::subpanelRows');
    $routes->get('documento/download/(:num)', 'Documents::download/$1');
    $routes->post('documento/delete/(:num)', 'Documents::delete/$1');
    $routes->get('propuesta', 'Proposals::index');
    $routes->match(['GET', 'POST'], 'propuesta/add', 'Proposals::add');
    $routes->match(['GET', 'POST'], 'propuesta/get_rows', 'Proposals::rows');
    $routes->get('propuesta/contactos', 'Proposals::contacts');
    $routes->get('propuesta/subpanel', 'Proposals::subpanel');
    $routes->get('propuesta/(:num)', 'Proposals::view/$1');
    $routes->match(['GET', 'POST'], 'propuesta/(:num)/edit', 'Proposals::edit/$1');
    $routes->post('propuesta/delete/(:num)', 'Proposals::delete/$1');
    $routes->match(['GET', 'POST'], 'reporte/seguimiento', 'Reports::followUp');
    $routes->get('reporte/seguimiento/export', 'Reports::followUpExport');
    $routes->match(['GET', 'POST'], 'reporte/cartera', 'Reports::wallet');
    $routes->get('reporte/cartera/export', 'Reports::walletExport');
    $routes->get('seguimiento', 'FollowUps::index');
    $routes->match(['GET', 'POST'], 'seguimiento/add', 'FollowUps::add');
    $routes->match(['GET', 'POST'], 'seguimiento/(:num)', 'FollowUps::edit/$1');
    $routes->match(['GET', 'POST'], 'seguimiento/get_rows', 'FollowUps::rows');
    $routes->post('seguimiento/delete/(:num)', 'FollowUps::delete/$1');
    $routes->post('seguimiento/selectRowForType', 'FollowUps::selectRowForType');
    $routes->post('seguimiento/get_rows_subpanel', 'FollowUps::subpanelRows');
    $routes->get('marca', 'Marca::index');
    $routes->match(['GET', 'POST'], 'marca/add', 'Marca::add');
    $routes->match(['GET', 'POST'], 'marca/(:num)', 'Marca::edit/$1');
    $routes->match(['GET', 'POST'], 'marca/get_rows', 'Marca::rows');
    $routes->post('marca/delete/(:num)', 'Marca::delete/$1');
    $routes->get('estado', 'Estado::index');
    $routes->match(['GET', 'POST'], 'estado/add', 'Estado::add');
    $routes->match(['GET', 'POST'], 'estado/(:num)', 'Estado::edit/$1');
    $routes->match(['GET', 'POST'], 'estado/get_rows', 'Estado::rows');
    $routes->get('sector', 'Sector::index');
    $routes->match(['GET', 'POST'], 'sector/add', 'Sector::add');
    $routes->match(['GET', 'POST'], 'sector/(:num)', 'Sector::edit/$1');
    $routes->match(['GET', 'POST'], 'sector/get_rows', 'Sector::rows');
    $routes->get('ucomercial', 'UComercial::index');
    $routes->match(['GET', 'POST'], 'ucomercial/add', 'UComercial::add');
    $routes->match(['GET', 'POST'], 'ucomercial/(:num)', 'UComercial::edit/$1');
    $routes->match(['GET', 'POST'], 'ucomercial/get_rows', 'UComercial::rows');
    $routes->post('ucomercial/delete/(:num)', 'UComercial::delete/$1');
    $routes->get('cgestion', 'CGestion::index');
    $routes->match(['GET', 'POST'], 'cgestion/add', 'CGestion::add');
    $routes->match(['GET', 'POST'], 'cgestion/(:num)', 'CGestion::edit/$1');
    $routes->match(['GET', 'POST'], 'cgestion/get_rows', 'CGestion::rows');
    $routes->post('cgestion/delete/(:num)', 'CGestion::delete/$1');
});

